logoutput: split
loglevel: debug
datafile: parameters.yml

process:
- source: etc
  operations:
  - destination: /tmp/raspi/etc
    regex: '.*\.template'
    permissions:
    - glob: '*/wpa_supplicant.conf'
      mode: "0640"
    - glob: '*/hostapd.conf'
      mode: "0640"
  - destination: /tmp/raspi/etc
    template: false

