#!/usr/bin/env bash
# File autogenerated by confinit
# These services are automatically enabled in systemd if their monit configuration
# exists in /etc/monit/conf-enabled. Systemd has a condition ConditionPathExists
# checking if monit has the configuration there.

# Avahi
{{ if .Data.avahi }}
echo -n "* Enable Avahi daemon ... "
pushd /etc/monit/conf-enabled >/dev/null
    ln -sf ../conf-available/avahi-daemon
popd
echo "done"
{{ else }}
echo -n "* Disable Avahi daemon ... "
rm -f /etc/monit/conf-enabled/avahi-daemon
echo "done"
{{ end }}

# Hostapd (wifi)
{{ if .Data.hostapd }}
echo -n "* Enable Hostapd daemon ... "
pushd /etc/monit/conf-enabled >/dev/null
    ln -sf ../conf-available/hostapd
popd
echo "done"
{{ else }}
echo -n "* Disable Hostapd daemon ... "
rm -f /etc/monit/conf-enabled/hostapd
echo "done"
{{ end }}

# Bluetooth
{{ if .Data.bluetooth }}
echo -n "* Enable Bluetooth daemon ... "
pushd /etc/monit/conf-enabled >/dev/null
    ln -sf ../conf-available/bluetoothd
popd
echo "done"
{{ else }}
echo -n "* Disable Bluetooth daemon ... "
rm -f /etc/monit/conf-enabled/bluetoothd
echo "done"
{{ end }}

# SSH
{{ if .Data.sshd }}
echo -n "* Enable SSH daemon ... "
pushd /etc/monit/conf-enabled >/dev/null
    ln -sf ../conf-available/openssh-server
popd
echo "done"
{{ else }}
echo -n "* Disable SSH daemon ... "
rm -f /etc/monit/conf-enabled/openssh-server
echo "done"
{{ end }}

# Prometheus Node Exporter
{{ if .Data.node_exporter }}
echo -n "* Enable Prometheus Node Exporter daemon ... "
pushd /etc/monit/conf-enabled >/dev/null
    ln -sf ../conf-available/node_exporter
popd
echo "done"
{{ else }}
echo -n "* Disable Prometheus Node Exporter daemon ... "
rm -f /etc/monit/conf-enabled/node_exporter
echo "done"
{{ end }}

# Docker
{{ if .Data.docker }}
echo -n "* Enable Docker daemon ... "
pushd /etc/monit/conf-enabled >/dev/null
    ln -sf ../conf-available/docker
popd
echo "done"
{{ else }}
echo -n "* Disable Docker daemon ... "
rm -f /etc/monit/conf-enabled/docker
echo "done"
{{ end }}

exit 0
